Added typings
lukeed/sockette pull request #27
Opened 2018-05-27 12:11 UTC by PatrickSachs

Merging the types into the main repository is definitely better than having a separate one, I agree(See PR #24).

Let me just explain the added files:

- **d/index.d.ts** - The definitions live here.
- **tsconfig.json** - Includes directives for the project that includes sockette on where to find the types, etc. Not a lot since we don't actually compile sockette using the TS compiler.

And obviously an added hint in the Readme. 
I just specified the latest Version of TypeScript in the package.json, although it should probably work with older ones as well. We're just really using any special features.

2018-05-27 16:22 UTC, lukeed requested changes
Hey, thanks for this!

I think this may be more than what we actually need for including typings.

A few of my repos have been PR'd with types & all you really need is the `*.d.ts` to be added, add that same file to `files` array in `package.json` and then add a new `"types": "{NAME}.d.ts"` to the `package.json` as well.

If things have drastically changed, let me know, but I dont imagine that they have.

2018-05-27 16:22 UTC, lukeed commented on readme.md
> +## TypeScript
Let's not include this. Those who have TS on will see it automatically.

2018-05-27 16:22 UTC, lukeed commented on tsconfig.json
> +{
_Pretty sure_ we don't need this file either.

2018-05-27 16:22 UTC, lukeed commented on package.json
> +  "typeScriptVersion": "2.8",
Don't need this bad boy.

2018-05-27 17:53 UTC, PatrickSachs commented
Okay, thanks for the info! Is the entry in files in package.json required? In my test environment it works without it. I also couldn't find any reference to this in the official guide: [https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)

2018-05-27 18:32 UTC, lukeed commented
Yeah, it's required. The `npm` registry only saves/uploads the contents of "files"  when specified. So it works on your machine because it exists for you already.

2018-05-28 18:22 UTC, lukeed approved these changes

2018-05-28 18:22 UTC, lukeed commented
Looks good, thank you~!

2018-05-28 18:23 UTC, merged